#!/usr/bin/env python
from pathlib import Path
from typing import List

from BCBio import GFF
from plumbum import cli

from src.filters.simple_filters import *
from src.util.annotation import Annotation
from src.util.locus_filter import LocusFilter


class LocusSolver(cli.Application):
    """Merge GFF3 files into single annotation set"""
    gff3_files: List[Path] = []
    output_path: Path = Path("/dev/stdout")
    tier: int = 1

    @cli.switch(["-i", "--input-gff3"], str, mandatory=True, list=True)
    def set_gff3_files(self, input_gff3s):
        """Path to annotation GFF3 file. Provide in expected priority sort order"""
        for file in input_gff3s:
            file = Path(file).resolve()
            if not file.exists() or not file.is_file():
                print(f"Unable to find gff3 file {str(file)}")
                exit(1)
            self.gff3_files.append(file)

    @cli.switch(["-o", "--output"], str)
    def set_output_path(self, output_path):
        """Path to output merged results, default stdout"""
        self.output_path = output_path

    @cli.switch(["-t", "--tier"], int)
    def set_tier(self, tier):
        """Set number of programs that must corroborate an input, default 1"""
        self.tier = tier

    def main(self):
        if len(self.gff3_files) < self.tier:
            print("Tier request surpasses input size, exiting")
            exit(1)
        annotation_models = []
        identifiers = []
        for identifier, gff3_file in enumerate(self.gff3_files):
            identifiers.append(str(identifier))
            annotation_models.append(Annotation(gff3_file, str(identifier)))
        locus_filter = LocusFilter(annotation_models=annotation_models)
        with open(self.output_path, "w") as merged_file:
            GFF.write(
                locus_filter.filter(Tier(self.tier, {i: model for i, model in enumerate(identifiers, start=1)})),
                merged_file
            )


if __name__ == "__main__":
    LocusSolver.run()
