#!/usr/bin/env python
from pathlib import Path

from BCBio import GFF
from plumbum import cli

from src.filters.simple_filters import *
from src.util.annotation import Annotation
from src.util.locus_filter import LocusFilter


class LocusSolver(cli.Application):
    VERSION = "0.1.0"
    """Merge GFF3 files into single annotation set"""
    output_path: Path = Path("/dev/stdout")
    tier: int = 1

    @cli.switch(["-o", "--output"], str)
    def set_output_path(self, output_path):
        """Path to output merged results, default stdout"""
        self.output_path = output_path

    @cli.switch(["-t", "--tier"], int)
    def set_tier(self, tier):
        """Set number of programs that must corroborate an input, default 1"""
        self.tier = tier

    def main(self, *gff3_files):
        if len(gff3_files) == 0:
            self.help()
            exit(0)
        if len(gff3_files) < self.tier:
            print("Tier request surpasses input size, exiting")
            exit(1)
        annotation_models = []
        identifiers = []
        for identifier, gff3_file in enumerate(gff3_files):
            gff3_file = Path(gff3_file).resolve()
            if not gff3_file.exists() or not gff3_file.is_file():
                print(f"Unable to find gff3 file {str(gff3_file)}")
                exit(1)
            identifiers.append(str(identifier))
            annotation_models.append(Annotation(gff3_file, str(identifier)))
        locus_filter = LocusFilter(annotation_models=annotation_models)
        with open(self.output_path, "w") as merged_file:
            GFF.write(
                locus_filter.filter(Tier(self.tier, {i: model for i, model in enumerate(identifiers, start=1)})),
                merged_file
            )


if __name__ == "__main__":
    LocusSolver.run()
